version: "3.7"
services:
  postgress:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: aimob
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4069412
      PGDATA: /var/lib/postgresql/data
    ports: 
      - 5432:5432
    volumes: 
      - postgres-data:/postgres:/var/lib/postgresql/data

volumes:
  postgres-data: