# fly.toml app configuration file generated for aimob on 2023-12-16T20:20:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aimob"
primary_region = "gru"

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = "npm run db:migrate"

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = ""
  internal_port = 0

  [[services.ports]]
    port = 8080
    handlers = ["http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
